[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfmake"]

[functions."process-reminders"]
  schedule = "0 * * * *"

[dev]
  command = "npm run dev"
  port = 4321
  targetPort = 4321
